### ISSUE TITLE
[be/trading-engine] load open order from DB on engine startup

### ISSUE THREAD

**Issue by tunggad** [beesEX/be#20]
Summary:
orderbook has to load open orders from DB on startup to restore the it's state after server shutdown or crash

Assumption:
All to be loaded open orders in DB were in sync with state of the orderbook at the time it was shuttdown or crashed and no trade execution activity was running -> do not put the orders through the matching logic again while loading 

Hints:
- the challenge is to restore the same state of the orderbook as before, means the the same order at each price level has to be restored.
- loading code should be synchronous and orderbook should not accept any event before the loading has completed

**Comment by hovietanh1991** [comment]
I'm not sure that you maybe plan to deploy this way in another module:

- During loading of orders in DB: new events are still received but will be held in temporal event storage.

- After loading from DB: new events are continuously held in this temporal event storage if it is not empty, while order book is pulling events from temporal event storage (principle: FIFO) and executes trade.

- After temporal event storage is empty: new events are received directly by order book to trade and no more saved in temporal event storage.

Advantage:
- During loading users feel comfortable because their place orders are still immediately executed

But this is more complex solution and cancel/update events must be also held on until order book is ready.

**Comment by tunggad** [comment]
Actually, the events sent between parent and child processes back an forth are already buffered in event queue of Node's eventing mechanism. So actually, while TE loads open orders from DB, order service in parent process can still send order event to beesV8, they will be queued by Node's eventing mechanism. We may need to increase the timeout for event rejection or queue capacity, so no event will be lost while TE is loading orders from DB.

For now, i don't want to change eventing/communication mechanism between parent process and child process, we would do that some time later, but for now it is a very time consuming task, we need time to do other  meaningful tasks first to complete our MVP as soon as possible :-)
